// Package testapp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20221217005803-d516da72dfb7 DO NOT EDIT.
package testapp

// V1FibonacciPostRequestBody defines model for V1FibonacciPostRequestBody.
type V1FibonacciPostRequestBody struct {
	// Position Position of a Fibonacci number in a sequence
	Position int64 `json:"position"`
}

// V1FibonacciPostResponseBody defines model for V1FibonacciPostResponseBody.
type V1FibonacciPostResponseBody struct {
	Data   V1FibonacciPostResponseBodyData `json:"data"`
	Errors []string                        `json:"errors"`
	Status bool                            `json:"status"`
}

// V1FibonacciPostResponseBodyData defines model for V1FibonacciPostResponseBodyData.
type V1FibonacciPostResponseBodyData struct {
	// Result Fibonacci number
	Result string `json:"result"`
}

// PostV1FibonacciJSONRequestBody defines body for PostV1Fibonacci for application/json ContentType.
type PostV1FibonacciJSONRequestBody = V1FibonacciPostRequestBody
